=== pypi-data/pypi-mirror-379/packages/postal-regex/postal_regex-1.0.0-py3-none-any.whl/postal_regex/data/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "required": [
      "country_code",
      "country_name",
      "postal_code_regex",
      "sample_valid",
      "sample_invalid"
    ],
    "properties": {
      "country_code": {
        "type": "string",
        "pattern": "^[A-Z]{2}$",
        "description": "ISO 3166-1 alpha-2 country code"
      },
      "country_name": {
        "type": "string",
        "minLength": 1
      },
      "postal_code_regex": {
        "type": "string",
        "description": "Regex for validating postal codes"
      },
      "sample_valid": {
        "type": "string",
        "description": "A valid postal code sample for this country"
      },
      "sample_invalid": {
        "type": "string",
        "description": "An invalid postal code sample for this country"
      }
    },
    "additionalProperties": false
  }
}

=== pypi-data/pypi-mirror-379/packages/postal-regex/postal_regex-1.0.0.tar.gz/postal_regex-1.0.0/src/postal_regex/data/postal_codes.json
[
  {"country_code": "IN", "country_name": "India", "postal_code_regex": "^[1-9][0-9]{5}$", "sample_valid": "110001", "sample_invalid": "000000"},
  {"country_code": "US", "country_name": "United States", "postal_code_regex": "^[0-9]{5}(?:-[0-9]{4})?$", "sample_valid": "12345-6789", "sample_invalid": "ABCDE"},
  {"country_code": "CA", "country_name": "Canada", "postal_code_regex": "^[A-Za-z]\\d[A-Za-z][ -]?\\d[A-Za-z]\\d$", "sample_valid": "K1A 0B1", "sample_invalid": "12345"},
  {"country_code": "GB", "country_name": "United Kingdom", "postal_code_regex": "^(GIR 0AA|[A-Z]{1,2}\\d[A-Z\\d]? \\d[ABD-HJLNP-UW-Z]{2})$", "sample_valid": "SW1A 1AA", "sample_invalid": "12345"},
  {"country_code": "DE", "country_name": "Germany", "postal_code_regex": "^[0-9]{5}$", "sample_valid": "10115", "sample_invalid": "ABCDE"},
  {"country_code": "FR", "country_name": "France", "postal_code_regex": "^[0-9]{5}$", "sample_valid": "75001", "sample_invalid": "1234"},
  {"country_code": "IT", "country_name": "Italy", "postal_code_regex": "^[0-9]{5}$", "sample_valid": "00100", "sample_invalid": "ABCDE"},
  {"country_code": "ES", "country_name": "Spain", "postal_code_regex": "^[0-9]{5}$", "sample_valid": "28013", "sample_invalid": "1234"},
  {"country_code": "AU", "country_name": "Australia", "postal_code_regex": "^[0-9]{4}$", "sample_valid": "2000", "sample_invalid": "12345"},
  {"country_code": "BR", "country_name": "Brazil", "postal_code_regex": "^\\d{5}-\\d{3}$", "sample_valid": "01001-000", "sample_invalid": "12345"},
  {"country_code": "RU", "country_name": "Russia", "postal_code_regex": "^[0-9]{6}$", "sample_valid": "101000", "sample_invalid": "ABCDE"},
  {"country_code": "CN", "country_name": "China", "postal_code_regex": "^[0-9]{6}$", "sample_valid": "100000", "sample_invalid": "12345"},
  {"country_code": "JP", "country_name": "Japan", "postal_code_regex": "^\\d{3}-\\d{4}$", "sample_valid": "100-0001", "sample_invalid": "1234567"},
  {"country_code": "MX", "country_name": "Mexico", "postal_code_regex": "^[0-9]{5}$", "sample_valid": "01000", "sample_invalid": "ABCDE"},
  {"country_code": "ZA", "country_name": "South Africa", "postal_code_regex": "^[0-9]{4}$", "sample_valid": "2000", "sample_invalid": "12345"},
  {"country_code": "NG", "country_name": "Nigeria", "postal_code_regex": "^[0-9]{6}$", "sample_valid": "100001", "sample_invalid": "ABCDE"},
  {"country_code": "AR", "country_name": "Argentina", "postal_code_regex": "^[A-Z]\\d{4}[A-Z]{3}$", "sample_valid": "C1000ABC", "sample_invalid": "12345"},
  {"country_code": "KR", "country_name": "South Korea", "postal_code_regex": "^[0-9]{5}$", "sample_valid": "04524", "sample_invalid": "ABCDE"},
  {"country_code": "SE", "country_name": "Sweden", "postal_code_regex": "^[0-9]{3} [0-9]{2}$", "sample_valid": "114 31", "sample_invalid": "12345"},
  {"country_code": "CH", "country_name": "Switzerland", "postal_code_regex": "^[1-9][0-9]{3}$", "sample_valid": "8001", "sample_invalid": "ABCDE"},
  {"country_code": "NL", "country_name": "Netherlands", "postal_code_regex": "^[1-9][0-9]{3} ?[A-Z]{2}$", "sample_valid": "1234 AB", "sample_invalid": "12345"},
  {"country_code": "BE", "country_name": "Belgium", "postal_code_regex": "^[1-9][0-9]{3}$", "sample_valid": "1000", "sample_invalid": "ABCDE"},
  {"country_code": "PL", "country_name": "Poland", "postal_code_regex": "^[0-9]{2}-[0-9]{3}$", "sample_valid": "00-001", "sample_invalid": "12345"},
  {"country_code": "SG", "country_name": "Singapore", "postal_code_regex": "^[0-9]{6}$", "sample_valid": "048616", "sample_invalid": "ABCDE"},
  {"country_code": "NZ", "country_name": "New Zealand", "postal_code_regex": "^[0-9]{4}$", "sample_valid": "6011", "sample_invalid": "12345"},
  {"country_code": "AE", "country_name": "United Arab Emirates", "postal_code_regex": "^[0-9]{5}$", "sample_valid": "00001", "sample_invalid": "ABCDE"}
]
